name: Development Deployment
on:
  push:
    branches: [{branch_name}]   #branch name, whenever push code to this branch, this action will run
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack starting
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: Discontract/github-action-slack-notify-deployment@v1
        with:
          channel: {slack_channel_name}    # Slack channel name
          status: STARTED
          color: warning

      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}     #AWS Secret Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   #AWS Secret Access Key
          aws-region: ap-southeast-2    #AWS region

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build React App        #Install libs and build
        run: npm install && npm run build
        env:
          CI: false
      - name: Deploy app build to S3 bucket    # Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://{bucket_name} --delete

      - name: invalidate     # Deploy app build to S3 bucket
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: 'E1XLGQ103LVDWO'
          PATHS: '/*'
          AWS_REGION: 'ap-southeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

       - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: Discontract/github-action-slack-notify-deployment@v1
        with:
          channel: {slack_channel_name}    # Slack channel name
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: Discontract/github-action-slack-notify-deployment@v1
        with:
          channel: {slack_channel_name}    # Slack channel name
          status: FAILED
          color: danger
     